version: '3'

services:
  db:
    image: 'mysql:8'
    ports:
           - "3310:3306"
    environment:
           - MYSQL_ROOT_PASSWORD=1111
           - MYSQL_DATABASE=login
           - MYSQL_USER=root
           - MYSQL_PASSWORD=1111
           - MYSQL_ROOT_HOST=%
    volumes:
           - ./my-datavolume:/var/lib/mysql
    healthcheck:
           test: ["CMD","mysqladmin","ping","-h","localhost"]
           timeout: 20s
           retries: 10
    restart: always
  backendserver:
    build: ./Login/
    ports:
           - "8081:8081"
#     links:
#            - "db"
    depends_on:
           - db
    restart: always
  frontend:
    build: ./my-app/
    links:
           - "backendserver"
    depends_on:
           - "backendserver"
    ports:
           - "80:80"      

  myredis:
    container_name: myredis
    image: redis
    restart: always
    ports:
      - 6379:6379 
    
#     command: redis-server /etc/redis/redis.conf --appendonly yes
#     volumes:
#       - ./redis/data:/data
#       - ./redis/conf/redis.conf:/etc/redis/redis.conf